"""
PDF Report Generator - Creates professional medical diagnosis reports using ReportLab.
Users can download their diagnosis as a clean PDF document.
"""
from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.units import inch, mm
from datetime import datetime

def generate_diagnosis_pdf(prediction, user):
    """Generate a professional PDF diagnosis report."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=30*mm, bottomMargin=20*mm, leftMargin=20*mm, rightMargin=20*mm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('ReportTitle', parent=styles['Title'], fontSize=22, textColor=colors.HexColor('#1a5276'), spaceAfter=6)
    subtitle_style = ParagraphStyle('Subtitle', parent=styles['Normal'], fontSize=10, textColor=colors.grey, spaceAfter=12)
    heading_style = ParagraphStyle('SectionHeading', parent=styles['Heading2'], fontSize=14, textColor=colors.HexColor('#2874a6'), spaceBefore=16, spaceAfter=8)
    body_style = ParagraphStyle('Body', parent=styles['Normal'], fontSize=10, leading=14, spaceAfter=6)
    disclaimer_style = ParagraphStyle('Disclaimer', parent=styles['Normal'], fontSize=8, textColor=colors.red, spaceBefore=20, leading=10)
    confidence_style = ParagraphStyle('Confidence', parent=styles['Normal'], fontSize=12, textColor=colors.HexColor('#27ae60'))

    elements = []

    # Header
    elements.append(Paragraph("Medical Diagnosis Report", title_style))
    elements.append(Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')} | Patient: {user.first_name or user.username} | Report #{prediction.id}", subtitle_style))
    elements.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#2874a6'), spaceAfter=12))

    # Diagnosis
    elements.append(Paragraph("Predicted Diagnosis", heading_style))
    elements.append(Paragraph(f"<b>{prediction.disease_name}</b>", ParagraphStyle('Disease', parent=body_style, fontSize=16, textColor=colors.HexColor('#1a5276'))))
    elements.append(Paragraph(f"Confidence: {prediction.confidence_score:.0%}", confidence_style))
    elements.append(Spacer(1, 8))

    # Causal Explanation
    elements.append(Paragraph("Why This Diagnosis (Causal Reasoning)", heading_style))
    elements.append(Paragraph(prediction.causal_explanation[:500], body_style))

    # Urgency
    elements.append(Paragraph("Urgency Level", heading_style))
    urgency_color = '#e74c3c' if 'immediate' in prediction.urgency_level.lower() else '#f39c12' if 'urgent' in prediction.urgency_level.lower() else '#27ae60'
    elements.append(Paragraph(f"<font color='{urgency_color}'><b>{prediction.urgency_level}</b></font>", body_style))

    # Medicines
    if prediction.recommended_medicines:
        elements.append(Paragraph("Recommended Medicines", heading_style))
        for med in prediction.recommended_medicines.split('|'):
            med = med.strip()
            if med:
                elements.append(Paragraph(f"• {med}", body_style))

    # Diet
    if prediction.diet_recommendations:
        elements.append(Paragraph("Diet & Nutrition", heading_style))
        elements.append(Paragraph(prediction.diet_recommendations.replace('|', ' • '), body_style))

    # Home Remedies
    if prediction.home_remedies:
        elements.append(Paragraph("Home Remedies", heading_style))
        elements.append(Paragraph(prediction.home_remedies.replace('|', ' • '), body_style))

    # Exercise
    if prediction.exercise_recommendations:
        elements.append(Paragraph("Exercise Recommendations", heading_style))
        elements.append(Paragraph(prediction.exercise_recommendations.replace('|', ' • '), body_style))

    # Specialist
    elements.append(Paragraph("Specialist Referral", heading_style))
    elements.append(Paragraph(f"Recommended: <b>{prediction.specialist_type}</b>", body_style))

    # Precautions
    if prediction.precautions:
        elements.append(Paragraph("Precautions & Warning Signs", heading_style))
        elements.append(Paragraph(prediction.precautions.replace('|', ' • '), body_style))

    # When to See Doctor
    if prediction.when_to_see_doctor:
        elements.append(Paragraph("When to Seek Emergency Care", heading_style))
        elements.append(Paragraph(prediction.when_to_see_doctor.replace('|', ' • '), body_style))

    # Disclaimer
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.grey, spaceBefore=20, spaceAfter=8))
    elements.append(Paragraph(
        "<b>DISCLAIMER:</b> This report was generated by an AI medical assistant and is NOT a substitute for "
        "professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or "
        "other qualified health provider. Do not disregard professional medical advice or delay seeking it "
        "because of information in this report. In case of a medical emergency, call your local emergency number immediately.",
        disclaimer_style
    ))
    elements.append(Paragraph(
        f"Generated by Antifragile Medical AI Chatbot | Causal AI + RAG Engine | {datetime.now().year}",
        ParagraphStyle('Footer', parent=styles['Normal'], fontSize=7, textColor=colors.grey, alignment=1)
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer
