# Generated by Django 6.0.3 on 2026-04-28 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(help_text='Was the diagnosis correct?')),
                ('correct_disease', models.CharField(blank=True, help_text='If wrong, what was the actual disease?', max_length=255, null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='diagnosis.diseaseprediction')),
            ],
            options={
                'db_table': 'user_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
