# Generated by Django 6.0.3 on 2026-04-28 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hospital_type', models.CharField(default='hospital', max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('distance_km', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'nearby_hospitals',
                'ordering': ['distance_km'],
            },
        ),
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255)),
                ('disease_id', models.CharField(blank=True, max_length=20)),
                ('confidence_score', models.FloatField(help_text='0.0 to 1.0')),
                ('causal_explanation', models.TextField(help_text='Why this disease was predicted')),
                ('symptoms_matched', models.TextField(help_text='Pipe-separated symptoms that matched')),
                ('causal_weights_used', models.TextField(blank=True, help_text='Causal weights applied')),
                ('urgency_level', models.CharField(default='Routine', max_length=100)),
                ('specialist_type', models.CharField(default='General Practitioner', max_length=255)),
                ('recommended_medicines', models.TextField(blank=True)),
                ('diet_recommendations', models.TextField(blank=True)),
                ('home_remedies', models.TextField(blank=True)),
                ('exercise_recommendations', models.TextField(blank=True)),
                ('lifestyle_changes', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('when_to_see_doctor', models.TextField(blank=True)),
                ('complications_if_untreated', models.TextField(blank=True)),
                ('alternative_diseases', models.JSONField(blank=True, default=list, help_text='List of alternative diagnoses with confidence scores')),
                ('rag_context_used', models.TextField(blank=True)),
                ('rag_relevance_score', models.FloatField(default=0.0)),
                ('full_llm_response', models.TextField(blank=True, help_text='Complete LLM generated response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='chat.chatsession')),
            ],
            options={
                'verbose_name': 'Disease Prediction',
                'verbose_name_plural': 'Disease Predictions',
                'db_table': 'disease_predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
