# Generated by Django 6.0.3 on 2026-04-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp')], default='web', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_diagnosis_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=255)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20, null=True)),
                ('duration', models.CharField(blank=True, help_text='e.g. 3 days, 1 week', max_length=100, null=True)),
                ('body_location', models.CharField(blank=True, help_text='e.g. head, chest, left arm', max_length=100, null=True)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'extracted_symptoms',
                'ordering': ['-extracted_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField(help_text='Message content in English')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('image', 'Image')], default='text', max_length=10)),
                ('original_language', models.CharField(default='en', max_length=10)),
                ('translated_content', models.TextField(blank=True, help_text='Original content if translated', null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='chat_audio/')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('image_analysis', models.TextField(blank=True, help_text='Vision AI analysis of uploaded image', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional message metadata', null=True)),
                ('tts_audio_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
    ]
